from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from datetime import datetime

def generate_pdf_report(filename, username, severity, features, recommendations):
    """Generate PDF report"""
    
    try:
        doc = SimpleDocTemplate(filename, pagesize=letter)
        elements = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=30,
            alignment=1
        )
        
        elements.append(Paragraph("InsomniAid Sleep Analysis Report", title_style))
        elements.append(Spacer(1, 0.3*inch))
        
        # User Info
        elements.append(Paragraph(f"<b>Patient Name:</b> {username.upper()}", styles['Normal']))
        elements.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))
        
        # Severity
        severity_color = {
            'No Insomnia': '#28a745',
            'Mild': '#ffc107',
            'Moderate': '#fd7e14',
            'Severe': '#dc3545'
        }
        
        severity_style = ParagraphStyle(
            'Severity',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor(severity_color.get(severity, '#dc3545')),
            spaceAfter=20
        )
        
        elements.append(Paragraph(f"Insomnia Severity: <b>{severity}</b>", severity_style))
        elements.append(Spacer(1, 0.2*inch))
        
        # Sleep Metrics Table
        elements.append(Paragraph("<b>Sleep Metrics Summary</b>", styles['Heading3']))
        
        metrics_data = [
            ['Metric', 'Value'],
            ['Sleep Efficiency', f"{features.get('sleep_efficiency_percent', 0):.1f}%"],
            ['Total Sleep Time', f"{features.get('total_sleep_time_min', 0):.1f} min"],
            ['Sleep Onset Latency', f"{features.get('sleep_onset_latency_min', 0):.1f} min"],
            ['Wake After Sleep Onset', f"{features.get('wake_after_sleep_onset_min', 0):.1f} min"],
            ['REM Latency', f"{features.get('rem_latency_min', 0):.1f} min"],
            ['REM Sleep', f"{features.get('percent_rem', 0):.1f}%"]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[3*inch, 2*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(metrics_table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Recommendations
        elements.append(Paragraph("<b>Personalized Recommendations</b>", styles['Heading3']))
        elements.append(Paragraph(recommendations['message'], styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))
        
        for tip in recommendations['tips']:
            elements.append(Paragraph(f"• {tip}", styles['Normal']))
        
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph(f"<b>Expected Duration:</b> {recommendations['duration']}", styles['Normal']))
        
        # Footer
        elements.append(Spacer(1, 0.4*inch))
        elements.append(Paragraph(
            "<i>This report is generated by InsomniAid AI system. For medical advice, consult a sleep specialist.</i>",
            styles['Normal']
        ))
        
        doc.build(elements)
        return True
    except Exception as e:
        print(f"Error generating PDF: {str(e)}")
        return False
